use anyhow::Result;
use browserx_core::Cookie;

/// Render cookies in the specified output format.
pub fn render_cookies(cookies: &[Cookie], format: &str) -> Result<()> {
    match format {
        "json" => render_json(cookies),
        "curl" => render_curl(cookies),
        "netscape" => render_netscape(cookies),
        "env" => render_env(cookies),
        "table" => render_table(cookies),
        _ => render_json(cookies),
    }
}

/// JSON output (default) -- machine-readable, structured.
fn render_json(cookies: &[Cookie]) -> Result<()> {
    let output: Vec<serde_json::Value> = cookies
        .iter()
        .map(|c| {
            serde_json::json!({
                "name": c.name,
                "value": c.value.expose(),
                "domain": c.domain,
                "path": c.path,
                "expires": c.expires,
                "secure": c.secure,
                "httpOnly": c.http_only,
                "sameSite": c.same_site,
                "source": c.source,
            })
        })
        .collect();

    println!("{}", serde_json::to_string_pretty(&output)?);
    Ok(())
}

/// curl-compatible output: `name1=value1; name2=value2`
///
/// Usage: `curl -b "$(browserx get --url https://x.com --format curl)" https://x.com/api`
fn render_curl(cookies: &[Cookie]) -> Result<()> {
    let header = browserx_core::to_cookie_header(cookies);
    println!("{header}");
    Ok(())
}

/// Netscape cookie.txt format (compatible with curl --cookie-jar).
///
/// Format: domain\tinclude_subdomains\tpath\tsecure\texpiry\tname\tvalue
fn render_netscape(cookies: &[Cookie]) -> Result<()> {
    println!("# Netscape HTTP Cookie File");
    println!("# Generated by browserx");
    println!("# https://github.com/justinhuangcode/browserx");
    println!();

    for c in cookies {
        let include_subdomains = if c.domain.starts_with('.') {
            "TRUE"
        } else {
            "FALSE"
        };
        let secure = if c.secure { "TRUE" } else { "FALSE" };
        let expiry = c.expires.unwrap_or(0);

        println!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}",
            c.domain,
            include_subdomains,
            c.path,
            secure,
            expiry,
            c.name,
            c.value.expose()
        );
    }

    Ok(())
}

/// Environment variable format.
///
/// Usage: `eval $(browserx get --url https://x.com --format env)`
fn render_env(cookies: &[Cookie]) -> Result<()> {
    for c in cookies {
        let var_name = c.name.to_uppercase().replace('-', "_").replace('.', "_");
        // Shell-safe value: escape single quotes
        let safe_value = c.value.expose().replace('\'', "'\\''");
        println!("export COOKIE_{var_name}='{safe_value}'");
    }

    Ok(())
}

/// Human-readable table format.
fn render_table(cookies: &[Cookie]) -> Result<()> {
    if cookies.is_empty() {
        println!("No cookies found.");
        return Ok(());
    }

    // Header
    println!(
        "{:<30} {:<25} {:<6} {:<8} {:<10}",
        "NAME", "DOMAIN", "SECURE", "HTTPONLY", "EXPIRES"
    );
    println!("{}", "-".repeat(85));

    for c in cookies {
        let expires = match c.expires {
            Some(ts) => browserx_core::util::epoch::expires_in_human(ts),
            None => "session".to_string(),
        };
        let name_display = if c.name.len() > 28 {
            format!("{}...", &c.name[..25])
        } else {
            c.name.clone()
        };

        println!(
            "{:<30} {:<25} {:<6} {:<8} {:<10}",
            name_display,
            c.domain,
            if c.secure { "yes" } else { "no" },
            if c.http_only { "yes" } else { "no" },
            expires.trim(),
        );
    }

    println!();
    println!("Total: {} cookies", cookies.len());

    Ok(())
}
